jytwitter/helper/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name="index"),
    path('<room_num>/', views.room, name="room")
]

jytwitter/jytwitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("twitterAnal.urls", namespace='jy')),
    path('helper/', include("helper.urls"))
]

jytwitter/twitterAnal/urls.py
from django.urls import path ,re_path
from . import views
app_name = "JY"
urlpatterns = [
    path('', views.main, name="main"),
    path(r'search/', views.search, name="search"),
    path(r'report/', views.report, name="report"),
    path('ajax/getData', views.getData, name='getData'), # ajax to send datas to client
    path('ajax/getSpecificDate', views.getData1, name='getData1')
]

jytwitter/helper/models.py
from django.db import models

# Create your models here.

jytwitter/helper/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json
def index(request):
    return render(request, 'helper/index.html', {})

def room(request, room_num):
    return render(request, 'helper/room.html', {
        'room_name' : mark_safe(json.dumps(room_num)),
    })

jytwitter/twitterAnal/views.py
from django.shortcuts import render, HttpResponse
from tweepy import Stream, OAuthHandler
import tweepy
from tweepy.streaming import StreamListener
import json, csv, os, redis
from datetime import datetime

def test():
    print("hello")
# 권한 키
c_key = '17NYW4W4x9eedwg8QywWuntm7'
c_s_key = 'LuyzvFr8m7RlsmvszuQaTQ8qYIvWmEtqW4G4ihVoJR8lhtFcoW'
a_key = '1108953758187180033-q5GhwoOGRdjo0eByNTzMUPgI0X6JPi'
a_s_key = 'VYfhk8OnyRRiUgvrMAnWosntolKlsFCMVYt4Zj4NplkoE'

# 추출 데이터 및 기초 변수
server_data = datetime.today().strftime("%Y%m%d")
datas = {
    'info' : {},
    'count' : [0, 0, 0],
    'menu' : {}
}
keywords = [
    ['짜장면', '탕수육', '짬뽕', '훠궈', '팔보채'],
    ['찌개', '비빔밥', '볶음', '수육', '나물', '국밥'],
    ['우동', '규동', '돈가스', '돈카츠', '카레', '초밥', '스시']
]

track_words = ['.', '!', '?', 'ㅋ', '짜장면', '탕수육', '짜장면', '탕수육', '짬뽕', '찌개', '밥', '비빔밥', '볶음', '팔보채', '훠궈',\
            '돈가스', '우동', '규동', '짜장', '카레']

def init_on_day():
    global datas
    datas = {
        'info' : {
            'data' : server_data,
        },
        'count' : [
            0, 0, 0
        ],
        'menu' : {
        }
    }
    
# 파일 쓰기
def csv_write(data):
    date_str = datetime.today().strftime("%Y%m%d")
    global server_data, datas
    if date_str > server_data:
        server_data = date_str
        init_on_day()

    # write json
    with open('j'+date_str+'.json', 'w', encoding='utf-8') as jw:
        json.dump(datas, jw)
        jw.close()

    # write csv
    with open('d'+date_str+'.csv', 'a', newline='\n', encoding='utf-8') as fw:
        w = csv.writer(fw)
        w.writerow([datetime.now(), data[0], data[1], data[2]])
        fw.close()

class listener(StreamListener):
    def on_status(self, data):
        #print(data.created_at, data.user.screen_name, data.id, data.text)
        for idx, key in enumerate(keywords):
            for word in key:
                if data.text.find(word) != -1:
                    dataset = [data.user.screen_name, data.id, data.text]
                    if not word in datas['menu'].keys():
                        datas['count'][idx] += 1
                        datas['menu'][word] = 1
                    else:
                        datas['menu'][word] += 1
                        datas['count'][idx] += 1
                    print(datas)
                    csv_write(dataset)
        return True

    def on_error(self, status_code):
        if status_code == 420:
            return False
        elif status_code == 401:
            print("401 Error Occured")
            return False

def init():
    auth = OAuthHandler(c_key, c_s_key)
    auth.set_access_token(a_key, a_s_key)
    api = tweepy.API(auth)
    try:
        twit_stream = Stream(auth, listener())
        twit_stream.filter(languages=['ko',], track=track_words, is_async=True)
    except:
        pass
    try:
        global datas
        date_str = datetime.today().strftime("%Y%m%d")
        json_data_file = open("j"+date_str+".json", "r", encoding="utf-8")
        datas = json.loads(json_data_file.read())
    except FileNotFoundError:
        pass

init()
def main(request):   
    return render(request, 'twitterAnal/index.html', {
        'datas' : json.dumps(datas, ensure_ascii=False),
    })

# send data by ajax
def getData(request):
    list_menu = list(datas['menu'])
    for i in range(len(list_menu)):
        for j in range(len(list_menu)):
            if datas['menu'][list_menu[i]] > datas['menu'][list_menu[j]]:
                tmp = list_menu[j]
                list_menu[j] = list_menu[i]
                list_menu[i] = tmp
    params = {
        'datas' : datas,
        'rank' : list_menu
    }
    data = json.dumps(params, ensure_ascii=False)
    return HttpResponse(data, content_type='json/application')


def search(request):
    return render(request, "twitterAnal/search_by_date.html")

def getData1(request):
    if request.method == 'POST':
        data = {}
        isExists = False
        date = request.POST.get('date')  
        date = date.replace('-', '')
        json_file = 'j'+date+'.json'
        if findFile(json_file):
            isExists = True
            data.update({'data' : json.loads(open(json_file, 'r').read())})
        data.update({'isExists' : isExists,})

        return HttpResponse(json.dumps(data, ensure_ascii=False), content_type='json/application')

def findFile(file_name):
    isExists = False
    if os.path.isfile(file_name): 
        isExists = True

    return isExists

def report(request):
    if request.method == 'POST':
        report_msg = request.POST.get('content')
        storeDataInRedis(report_msg)
    return render(request, 'twitterAnal/report.html')

### redis ##
report_cnt = 0
def storeDataInRedis(message):
    global report_cnt
    try:
        r = redis.StrictRedis(host="localhost", port=6379, password="", decode_responses=True)
        r.set(report_cnt, message)
        report_cnt = report_cnt + 1

        for message in r.keys():
            print(r.get(message))
    except Exception as error:
        print(error)

jytwitter/helper/templates/helper/index.html
<html>
<head>
<body>  
<input id="room" type="text">
<button onclick="gotoRoom();">입장</button>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script>
function gotoRoom(){
    var room_num =  $("#room").val();
    window.location.href = '/helper/'+ room_num + '/';
}
</script>
</body>
</head>
</html>

jytwitter/helper/templates/helper/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = {{ room_name }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        console.log(e);
        var data = JSON.parse(e.data);
        var message = data['messeage'];
            console.log(message);
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>

jytwitter/twitterAnal/templates/twitterAnal/header.html
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Data Analysis</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  </head>
  <body>

    <div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation"  id="realtime_btn"><a href="{% url 'jy:main' %}">실시간 조회</a></li>
            <li role="presentation" id="saerch_by_date_btn"><a href="{% url 'jy:search' %}">일별 조회</a></li>
            <li role="presentation" id="report"><a href="{% url 'jy:report' %}">오류 보고</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Data Analysis</h3>
      </div>
      <div>
        {% block content %}{% endblock %}   
      </div>

      <div id="rank" class="text-center"></div>

      <footer class="footer">
        <p>&copy; AHN JUYOUNG</p>
        <div id="helper"></div>
      </footer>

    </div> <!-- /container -->

    <script src="http://code.jquery.com/jquery-2.0.0.js"></script>  
    <script>
        $("li").on("click", function(){
            recent_btn = $(this).attr("id");
           $(this).addClass("active");
        })

        $("#helper").load("/helper/ajy/");
    
    </script>
  </body>
</html>

jytwitter/twitterAnal/templates/twitterAnal/index.html
{% extends 'twitterAnal/header.html' %}
{% block content %}
    <div style="font-size : 30px"><span id="time"></span></div>
    <input type="button" class="btn btn-info" onclick="getData();" value="수동 갱신">
    <div id="datas"></div>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://code.jquery.com/jquery-2.0.0.js"></script>  
    <script>
        $(document).ready(function(){
            getData();
            timeAlarm();
            ranking();
        })

        // 각각 데이터를 담아 둘 변수
        var menu_list = [];
        var datas = {};
        var datas1 = {};
        var colors = ['#0b62a4', '#DCE775', '#F48FBE', '#EC407E', '#7B1FA2', '#5E35BE','#BBDEFE', '#64B5FE', '#5C6BC0', '#303F9F', '#1565CE', '#82B1FE', '#80DEEE', '#00E5FE','#81C78E', '#00796B', '#5F6460'];
        // 10초마다 갱신
        setInterval(getData, 10000);
        setInterval(timeAlarm, 1000);
        function timeAlarm(){
            $("span#time").html(new Date(Date.now()));
        }

        // ajax로 데이터를 받아와 처리
        function getData(){
            $.ajax({
                url : "{% url 'JY:getData' %}",
                type : "GET",
                data : {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function(res)
                {
                    datas = res.datas;
                    ranking();
                    //ranking(res.rank);
                    //$("#rank").html(res.rank + " ");
                    Data_to(datas);
                }
            })
        }
        // 받아온 데이터 가공
        function Data_to(a)
        {
            menu_list = Object.keys(a.menu);
            datas1 = a.menu;
            datas1['y'] = "Twitter Datas Analysis by AJY";
            showGraph();
        }

        
        function ranking()
        { 
            $("#rank").empty();
            menu_list.forEach(function(menu, index) {
                var span = $("<span></span>");
                span.text(menu).prepend("<span>　</span>");
                span.find("span").css("background-color", colors[index]);
                $("#rank").append(span);
            });
        }


        // 가공한 데이터 그리기
        function showGraph(){
            $("#datas").empty();
            Morris.Bar({
                element: 'datas',
                data: [
                    datas1,
                ],
                barColors : colors,
                xkey: "y",
                ykeys: menu_list,
                labels: menu_list,
                hideHover : true
            });
        }
    </script>
{% endblock %}

jytwitter/twitterAnal/templates/twitterAnal/report.html
{% extends 'twitterAnal/header.html' %}
{% load static %}

{% block content %}
    <form method="POST" action="{% url 'jy:report' %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="reportError">오류 내용 및 건의사항</label>
          <textarea class="form-control" id="report" name="content" placeholder="오류 사항 및 건의사항 입력"></textarea>
          <small id="reportHelp" class="form-text text-muted">해당 내용은 서버에 저장됩니다.</small>
        </div>
        <input class="btn btn-primary" type="submit" value="전송" onclick="alerting()">
    </form>


    <script>
        function alerting()
        {
            alert("소중한 의견 감사합니다.");
        }
        
    </script>
{% endblock %}

jytwitter/twitterAnal/templates/twitterAnal/search_by_date.html
{% extends 'twitterAnal/header.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <input id="date" type="date"><input id="search" style="margin-left : 5px;" class="btn btn-info" type="button" value="조회" onclick="search_by_date();">
    </div>
    <div style="font-size : 30px"><span id="time"></span></div>
    <div id="datas"></div>
    <div id="rank"></div>

    <script src="http://code.jquery.com/jquery-2.0.0.js"></script>  
    <script>
        $(document).ready(function(){
            var now = new Date();
            var day = ("0" + now.getDate()).slice(-2);
            var month = ("0" + (now.getMonth() + 1)).slice(-2);
            $("#date").val(now.getFullYear()+"-"+month+"-"+day);
        })
        
         function showGraph(datas){
            var colors = ['#0b62a4', '#DCE775', '#F48FBE', '#EC407E', '#7B1FA2', '#5E35BE','#BBDEFE', '#64B5FE', '#5C6BC0', '#303F9F', '#1565CE', '#82B1FE', '#80DEEE',
                         '#00E5FE','#81C78E', '#00796B', '#5F6460'];
            var menu_list = Object.keys(datas.menu); 
            var datas1 = datas.menu;
            datas1['y'] = 'Twitter Data Anaylsis by AJY';
            $("#time").html($("#date").val());
            $("#datas").empty();
            Morris.Bar({
                element: 'datas',
                data: [
                    datas1,
                ],
                barColors : colors,
                xkey: "y",
                ykeys: menu_list,
                labels: menu_list,
                hideHover : true
            });
            sorting(datas);
        }


        function search_by_date(){
            var date = $("#date").val();
            if(date == ""){
                alert("날짜를 선택해 주세요.");
            }else{
                 $.ajax({
                    type : "POST",
                    url : "{% url 'jy:getData1' %}",
                    data : {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'date' : date
                    },
                    success : function(res){
                        if (res.isExists == false){
                            alert("해당 일자에는 데이터 파일이 존재하지 않습니다.");
                        }else{
                            alert("해당 일자의 데이터 파일이 존재하여 로드합니다.");
                            showGraph(res.data);
                        }
                    },
                    error : function(a, b, c){
                        alert(a + " " + b + " " + c);
                    }
                })
            }
        }
        function sorting(data)
        {
            $("#rank").empty();
            var menu_list = Object.keys(data.menu);
            for (var i=0; i<menu_list.length; i++)
            {
                for (var j=i; j<menu_list.length; j++)
                {
                    if (data.menu[menu_list[i]] < data.menu[menu_list[j]])
                    {
                        var tmp = menu_list[i];
                        menu_list[i] = menu_list[j];
                        menu_list[j] = tmp;
                    }
                }
            }
            
            var table_ = $("<table class=\"mt-5 table table-sm table-hover text-center table-border\"></table>");
            table_.prepend("<tr style='background-color : rgb(253, 234, 123)'><td>순위</td><td>메뉴</td><td>언급횟수</td></tr>");
            menu_list.forEach(function(item, index) {
                if(item != 'y'){
                    table_.append("<tr><td>"+(index+1)+"</td><td>"+item+"</td><td>"+data.menu[item]+"</td></tr>");
                }
            });  
            $("#rank").html(table_);
        }
    </script>
{% endblock %}